Add missing includes
Without this patch, gcc10 compilation issued warnings such as
 src/terminal/colors.c:85:2: warning: implicit declaration of function ]
     85 |  v3270_emit_save_settings(widget);